export default Object.freeze({
    GET_REPOS_REQUEST: 'GET_REPOS_REQUEST',
    GET_REPOS_SUCCESS: 'GET_REPOS_SUCCESS',
    GET_REPOS_FAILURE: 'GET_REPOS_FAILURE',
    UPDATE_SEARCH_INFO: 'UPDATE_SEARCH_INFO',
});
